esphome:
  name: gas-sensor
  friendly_name: Gas Sensor BME680

esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  framework:
    type: esp-idf

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true

bme68x_bsec2_i2c:
  address: 0x76
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V

# sensor
sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "BME68x Temperature"
    pressure:
      name: "BME68x Pressure"
    humidity:
      name: "BME68x Humidity"
    iaq:
      name: "BME68x IAQ"
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"

#deep_sleep:
#  id: deep_sleep_component
#  run_duration: 30s
#  sleep_duration: 5min
##  wakeup_pin:
##    number: GPIO5
##    mode: INPUT_PULLUP
##    inverted: true

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "kU3HLTder+TpT6k3lBdVtI0sXH5VkOV7P5zltLYvegA="

ota:
  - platform: esphome
    password: "84784a88b1e7410710abe9d93a81e1e2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gas-Sensor Fallback Hotspot"
    password: "wM0IHmNgMmme"

captive_portal:
    