esphome:
  name: temp-sensor
  friendly_name: Temp Sensor AHT20

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: esp-idf

i2c:
 sda: GPIO5
 scl: GPIO6
 scan: true

# sensor
sensor:
  - platform: aht10
    variant: AHT20
  
    update_interval: 1min

    temperature:
      name: "Temperature"

    humidity:
      name: "Humidity"

#deep_sleep:
#  id: deep_sleep_component
#  run_duration: 30s
#  sleep_duration: 5min
##  wakeup_pin:
##    number: GPIO5
##    mode: INPUT_PULLUP
##    inverted: true

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "ajmnoL6VqHb+Mqzp5S28/AEKSe0P7LnuEvuevpBvk3s="

ota:
  - platform: esphome
    password: "7019a5f1b53267370f70cd5203b4d5c5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Sensor Fallback Hotspot"
    password: "qsVj7gyzwtHN"

captive_portal:
    